/**
 * Builder Agent - Cloudflare Workers Edition
 * Hades Army v0.8.0
 */

import { logger } from "../utils/logger";
import { generateId } from "../utils/helpers";

export interface BuildTask {
  id: string;
  specification: string;
  language: string;
  requirements: string[];
}

export interface BuildResult {
  taskId: string;
  language: string;
  files: Array<{ path: string; content: string }>;
  confidence: number;
  estimatedLines: number;
}

export class BuilderAgent {
  async build(task: BuildTask): Promise<BuildResult> {
    logger.info(`Builder: Starting build ${task.id}`);
    const requirements = await this.analyzeRequirements(task.specification);
    const complexity = await this.estimateComplexity(task);

    return {
      taskId: task.id,
      language: task.language,
      files: this.generateFiles(task, requirements),
      confidence: Math.min(0.95, 0.7 + requirements.length * 0.05),
      estimatedLines: complexity.lines,
    };
  }

  async analyzeRequirements(specification: string): Promise<string[]> {
    return specification
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.startsWith("-") || line.startsWith("*"))
      .map((line) => line.replace(/^[-*]\s*/, ""));
  }

  async estimateComplexity(task: BuildTask): Promise<{ lines: number; time: number; risk: string }> {
    const specLength = task.specification.length;
    const reqCount = task.requirements.length;
    const lines = Math.max(50, specLength / 10 + reqCount * 20);
    const time = Math.max(1, lines / 100);
    const risk = lines > 500 ? "high" : lines > 200 ? "medium" : "low";
    return { lines: Math.round(lines), time: Math.round(time), risk };
  }

  private generateFiles(task: BuildTask, requirements: string[]): Array<{ path: string; content: string }> {
    return [
      {
        path: `src/generated/${task.id}.ts`,
        content: `// Auto-generated by Hades Army Builder\n// Task: ${task.id}\n\n${task.specification}`,
      },
    ];
  }
}

export const builderAgent = new BuilderAgent();
